// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKu63SL_aly_BnIZOyzTPpbby6xFjmdUg',
    appId: '1:515482903384:web:fd430e4a14aa922d4dbb2d',
    messagingSenderId: '515482903384',
    projectId: 'fashion-app-5b93d',
    authDomain: 'fashion-app-5b93d.firebaseapp.com',
    storageBucket: 'fashion-app-5b93d.appspot.com',
    measurementId: 'G-WJJHX1JLN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARCoS13nztQtJdJq7vKFvUSIBin0xIG4I',
    appId: '1:515482903384:android:78d14362dcced1e84dbb2d',
    messagingSenderId: '515482903384',
    projectId: 'fashion-app-5b93d',
    storageBucket: 'fashion-app-5b93d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMKGbU6fZVcHEej9UqkSQGkPk79uW7RfI',
    appId: '1:515482903384:ios:9322a79de764c8b54dbb2d',
    messagingSenderId: '515482903384',
    projectId: 'fashion-app-5b93d',
    storageBucket: 'fashion-app-5b93d.appspot.com',
    iosBundleId: 'com.example.fashion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMKGbU6fZVcHEej9UqkSQGkPk79uW7RfI',
    appId: '1:515482903384:ios:d050942725cb68d34dbb2d',
    messagingSenderId: '515482903384',
    projectId: 'fashion-app-5b93d',
    storageBucket: 'fashion-app-5b93d.appspot.com',
    iosBundleId: 'com.example.fashion.RunnerTests',
  );
}
